### ISSUE TITLE
The project doesn't build

### ISSUE THREAD

**Issue by adrienvaucard** [HugoHUET/Zork#1]
I can't build your project :(

**Comment by HugoHUET** [comment]
Hi, can you send us more details on your error pls ?

**Comment by PaulLereverend** [comment]
Hi @adrienvaucard 

Thank you for your feedback 🚀 
Unfortunately we cannot reproduce your issue. 
Have you tried reseting the router and connecting through ethernet instead of wifi. 

Cheers

**Comment by adrienvaucard** [comment]
Ok, I reconnected my Livebox from Orange and it worked. Thanks guys !
